# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b360a1ee8b4d667a4ed40d0ff801a364"
name = "metafield-visualizer-a"
application_url = "https://app.metafieldinspector.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "themes/update" ]
  uri = "/webhooks/themes/update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_themes"

[auth]
redirect_urls = [ "https://app.metafieldinspector.com/api/auth" ]

[app_proxy]
url = "https://app.metafieldinspector.com/api/proxy"
subpath = "mf-inspector"
prefix = "apps"
